// Generated by mkhdr

#ifndef HEADER_MSG
#define HEADER_MSG

struct MSG {
    unsigned int message;
    unsigned long u_param;
    long l_param;
};


//-----------------------------------------------------------------------------
// メッセージ処理

typedef void (*ONSEN_PROC) (unsigned int, unsigned long, long);

int get_message(struct MSG *msg);
int peek_message(struct MSG *msg);
void dispatch_message(const struct MSG *msg, ONSEN_PROC proc);

//-----------------------------------------------------------------------------
// メッセージ

void send_window_active_msg(int pid_recieve, int pid);
void send_window_deactive_msg(int pid_recieve, int pid);

//-----------------------------------------------------------------------------
// メッセージ定義


// ---- アプリケーション終了依頼メッセージ
// u_param : 終了させるアプリケーションの PID
// l_param : 終了コード
#define MSG_REQUEST_EXIT  0


// ---- タイマメッセージ
// u_param : タイマID
#define MSG_TIMER    1


// ---- 割り込みメッセージ（Ctrl + C により発生する）
#define MSG_INTR     2


// ---- キーコードメッセージ
// u_param : キーコード
#define MSG_KEYDOWN  3


// ---- 文字メッセージ
// u_param : 文字
#define MSG_CHAR     4


// ---- 生マウスメッセージ
// u_param : データ
#define MSG_RAW_MOUSE  5


// ---- クリックメッセージ
// l_param : 下位16ビット：x, 上位16ビット：y
#define MSG_LEFT_DOWN     6
#define MSG_LEFT_UP       7
#define MSG_RIGHT_DOWN    8
#define MSG_RIGHT_UP      9
#define MSG_CENTER_DOWN  10
#define MSG_CENTER_UP    11


// ---- 子タスクの終了通知メッセージ
// u_param : 子タスクの PID
// l_param : 終了ステータス
#define MSG_NOTIFY_CHILD_EXIT   12


// ---- ウィンドウアクティブメッセージ
// u_param : アクティブになったウィンドウの PID
#define MSG_WINDOW_ACTIVE    13


// ---- ウィンドウ非アクティブメッセージ
// u_param : 非アクティブウィンドウの PID
#define MSG_WINDOW_DEACTIVE    14


// ---- ネットワークメッセージ
#define MSG_NET_RX    15
#define MSG_NET_TX    16

#endif
