// Generated by mkhdr

#ifndef HEADER_ATA_INFO
#define HEADER_ATA_INFO

#include <stdbool.h>
#include <stdint.h>
#include "ata/common.h"


#define SUPPORT_PIO_MODE3  1
#define SUPPORT_PIO_MODE4  2


struct ATA_INFO {
    uint16_t default_cylinders;  // 論理シリンダ数（デフォルト転送モード）
    uint16_t default_heads;      // 論理ヘッド数  （デフォルト転送モード）
    uint16_t default_sectors;    // 論理セクタ数  （デフォルト転送モード）
    uint16_t cur_cylinders;      // 論理シリンダ数（現在の転送モード）
    uint16_t cur_heads;          // 論理ヘッド数  （現在の転送モード）
    uint16_t cur_sectors;        // 論理セクタ数  （現在の転送モード）
    uint8_t support_pio_mode;
    bool support_lba;
    bool support_iordy;
    bool support_pow_mng;
};


void ata_anal_id(struct ATA_DEV *dev);


#endif
