// Generated by mkhdr

#ifndef HEADER_NET_ETHER
#define HEADER_NET_ETHER

#include <stdint.h>


#define ETH_TYPE_IP   0x0080
#define ETH_TYPE_IPv6 0xDD86


struct ETH_HEADER {
    uint8_t dst_mac[6];
    uint8_t src_mac[6];
    uint16_t len_type;
};


void eth_handler(struct ETH_HEADER *eth, int len);


#endif
