// Generated by mkhdr

#ifndef HEADER_INTR
#define HEADER_INTR

//-----------------------------------------------------------------------------
// 割り込み

void intr_init(void);

void notify_intr_end(unsigned char irq);

void set_pic0_mask(unsigned char mask);
void set_pic1_mask(unsigned char mask);

//-----------------------------------------------------------------------------
// フォールト


#endif
