// Generated by mkhdr

#ifndef HEADER_PAGING
#define HEADER_PAGING


//-----------------------------------------------------------------------------
// ページング

#define PAGE_SIZE_B 4096  ///< ページサイズ

#define IS_4KB_ALIGN(byte) (((byte) & 0xFFF) == 0)  ///< 4KB 境界であるか確認
#define CEIL_4KB(byte)  (((byte) + 0xFFF) & ~0xFFF) ///< 4KB 単位で切り上げ
#define FLOOR_4KB(byte) ((byte) & ~0xFFF)           ///< 4KB 単位で切り捨て

#define BYTE_TO_PAGE(byte) ((CEIL_4KB(byte)) >> 12)


void paging_init(void);
unsigned long *get_os_pd(void);

void paging_dbg(void);


//-----------------------------------------------------------------------------
// ページ単位メモリ管理

void page_mem_init(void);
unsigned int total_free_page(void);
void *page_alloc(unsigned int num_page);
int page_free(void *maddr);
int page_set_free(void *vp_vaddr, unsigned int num_page);
void *get_mem_mng(void);

void page_mem_dbg();

#endif
