// Generated by mkhdr

#ifndef HEADER_STRING
#define HEADER_STRING

int s_len(const char *s);
void s_cpy(char *s, const char *t);
void s_cat(char *s, const char *t);
void s_reverse(char *s);
int s_cmp(const char *s, const char *t);
int s_ncmp(const char *s, const char *t, int n);

void s_to_upper(char *s);

void s_itox(int n, char *s, int digit);
void s_itoa(int n, char *s);
int  s_atoi(const char *s);
void s_size(unsigned int size_B, char *s);

void s_dbg_int(char *s, const char *name, unsigned int var);
void s_dbg_intx(char *s, const char *name, unsigned int var);
void s_dbg_shortx(char *s, const char *name, unsigned short var);

int memcmp(const void *buf1, const void *buf2, unsigned int);
void *memcpy(void *dst, const void *src, unsigned int);
void *memmove(void *dst, const void *src, unsigned int);
void *memset(void *dst, int c, unsigned int count);

#endif
