// Generated by mkhdr

#ifndef HEADER_TIMER
#define HEADER_TIMER

#define ERROR_TID  -1

#define TIMER_MAX 512

void timer_init(void);
int  timer_new(void);
void timer_free(int tid);
void timer_task_free(int pid);
void timer_start(int tid, unsigned int timeout_ms);
int  timer_stop(int tid);
unsigned int timer_get_count_10ms(void);
void int20_handler(int *esp);

#endif
