// Generated by mkhdr

#ifndef HEADER_INTHANDLER
#define HEADER_INTHANDLER

void asm_int00_handler(void);
void asm_int05_handler(void);
void asm_int06_handler(void);
void asm_int07_handler(void);
void asm_int0A_handler(void);
void asm_int0B_handler(void);
void asm_int0C_handler(void);
void asm_int0D_handler(void);
void asm_int0E_handler(void);

void asm_int20_handler(void);
void asm_int21_handler(void);
void asm_int2C_handler(void);

#endif
