// Generated by mkhdr

#ifndef HEADER_FS_EXT2
#define HEADER_FS_EXT2

#include <stdint.h>

#define EXT2_ROOT_INODE  2

struct DIRECTORY {
    void *head;
    struct DIRECTORY_ENTRY *cur_ent;
};


struct DIRECTORY_ENTRY {
    uint32_t inode_i;
    uint16_t total_size;
    uint8_t name_len;
    uint8_t type;
    char name[];
};


void ext2_init(void);
int ext2_get_inode_i(int parent_inode_i, const char *name);
int ext2_get_file_size_B(int inode_i);
void *ext2_open(int inode_i, int *len);
struct DIRECTORY *ext2_open_dir(int inode_i);
struct DIRECTORY_ENTRY *ext2_read_dir(struct DIRECTORY *dir);
void ext2_close_dir(struct DIRECTORY *dir);

#endif
