// Generated by mkhdr

#ifndef HEADER_FAT12
#define HEADER_FAT12

struct FILEINFO {
    char name[8];
    char ext[3];
    unsigned char type;
    char reserve[10];
    unsigned short time;
    unsigned short data;
    unsigned short clustno;
    unsigned int size;
};


void fat12_init(void);
struct FILEINFO *fat12_get_file_info(void);
void fat12_load_file(int clustno, int size, char *buf);
int fat12_search_file(struct FILEINFO *fi, const char *fname);


#endif
