// Generated by mkhdr

#ifndef HEADER_FAT12
#define HEADER_FAT12

typedef struct FILEINFO {
    char name[8];
    char ext[3];
    unsigned char type;
    char reserve[10];
    unsigned short time;
    unsigned short data;
    unsigned short clustno;
    unsigned int size;
} FILEINFO;


void fat12_init(void);
FILEINFO *fat12_get_file_info(void);
void fat12_load_file(int clustno, int size, char *buf);
int fat12_search_file(FILEINFO *fi, char *fname);


#endif
