// Generated by mkhdr

#ifndef HEADER_GBUFFER
#define HEADER_GBUFFER

#include <stdbool.h>
#include "graphic.h"

#define GBF_FLG_HAS_COLORKEY    (1 << 0)
#define GBF_FLG_HAS_ALPHA       (1 << 1)

struct _GBUFFER_METHOD;

struct GBUFFER {
    void *buf;

    int w;
    int h;
    int color_width;

    unsigned int flags;

    COLOR32 colorkey;  // 透明にする色。SRF_FLG_HAS_COLORKEYで有効。
    unsigned char alpha;

    struct GBUFFER_METHOD *m;
};


struct GBUFFER_METHOD {
    COLOR32 (*get)(struct GBUFFER *self, int x, int y);
    void (*put)(struct GBUFFER *self, int x, int y, COLOR32 color);
    void (*fill_rect)(struct GBUFFER *self, int x, int y, int w, int h, COLOR32 color);
    void (*blit)(struct GBUFFER *self, int src_x, int src_y, int w, int h, struct GBUFFER *dst, int x, int y, int op);
};


extern struct GBUFFER_METHOD *g_gbuf_method16;

#endif
