// Generated by mkhdr

#ifndef HEADER_IDT
#define HEADER_IDT

// API(システムコール)を呼び出すときの割り込み番号
#define IDT_API_NO  (0x44)


void idt_init(void);
void set_gate_desc(int no, unsigned short sel, void (*f)(void),
        int count, int type, int dpl);

#endif
