// Generated by mkhdr

#ifndef HEADER_KEYBOARD
#define HEADER_KEYBOARD

#include <stdbool.h>


#define PORT_RW_KBC_DATA            0x0060
#define KBC_DATA_ENABLE_MOUSE_MODE    0x47

#define PORT_R_KBC_STATE            0x0064
#define KBC_STATE_SEND_NOT_READY      0x02

#define PORT_W_KBC_CMD              0x0064
#define KBC_CMD_WRITE_MODE            0x60
#define KBC_CMD_SENDTO_MOUSE          0xD4


void int21_handler(int *esp);
void wait_kbc_sendready(void);
char keycode2char(int keycode, bool is_shift_on);

#endif
