// Generated by mkhdr

#ifndef HEADER_MSG_Q
#define HEADER_MSG_Q

#include "msg.h"

void msg_q_init(int pid);
int  msg_q_put(int pid, struct MSG *msg);
int  msg_q_get(int pid, struct MSG *msg);
int  msg_q_size(int pid);

#endif
