// Generated by mkhdr

#ifndef HEADER_PAGING
#define HEADER_PAGING


//-----------------------------------------------------------------------------
// ページング

#define PAGE_SIZE_B (4096)  // ページサイズ
#define CUR_PD      (VADDR_PD_SELF)

#define PTE_PRESENT (0x001)  // 1ならページがメモリ上に存在する
#define PTE_RW      (0x002)  // 0なら特権レベル3では書き込めない
#define PTE_US      (0x004)  // 0なら特権レベル3ではアクセスできない
#define PTE_ACCESS  (0x020)  // このエントリのページをアクセスするとCPUが1にする
#define PTE_DIRTY   (0x040)  // このエントリのページに書き込むとCPUが1にする
#define PTE_4MB     (0x080)  // 4MBページ

/* メモリ管理用 */
#define PTE_START   (0x200)  // 連続領域開始。カスタムフラグ
#define PTE_CONT    (0x400)  // 連続領域続く。カスタムフラグ
#define PTE_END     (0x800)  // 連続領域終了。カスタムフラグ

#define IS_4KB_ALIGN(byte) (((unsigned long) (byte) & 0xFFF) == 0)  // 4KB 境界であるか確認
#define CEIL_4KB(byte)  (((byte) + 0xFFF) & ~0xFFF) // 4KB 単位で切り上げ
#define FLOOR_4KB(byte) ((byte) & ~0xFFF)           // 4KB 単位で切り捨て

#define BYTE_TO_PAGE(byte) ((CEIL_4KB(byte)) >> 12)

#define VADDR_TO_PD_INDEX(vaddr)  (((unsigned long) vaddr) >> 22)
#define VADDR_TO_PT_INDEX(vaddr)  ((((unsigned long) vaddr) >> 12) & 0x3FF)

#define BASE_PD_I  VADDR_TO_PD_INDEX(VADDR_BASE)


typedef unsigned long PDE;
typedef unsigned long PTE;

void paging_init(void);
void paging_map(void *vp_vaddr, void *vp_maddr, int flg);
void *paging_get_maddr(void *vp_vaddr);
PDE *create_user_pd(void);
int paging_get_flags(void *vp_vaddr);

void app_area_copy(PDE *pd);
void app_area_clear(void);

void paging_dbg(void);

#endif
