// Generated by mkhdr

#ifndef HEADER_PCI
#define HEADER_PCI

#include <stdint.h>

// PCI
struct PCI_CONF {
    int bus;
    int dev;
    int func;

    uint32_t io_addr;
    uint32_t mm_addr;

    uint16_t dev_id;
    uint16_t vendor_id;
    uint16_t status;
    uint16_t cmd;
    uint8_t  cls;
    uint8_t  sub_cls;
    uint8_t  prog_if;
    uint8_t  rev;
    uint8_t  header_type;
    uint32_t base_addr[6];
    uint8_t  irq_pin;
    uint8_t  irq_line;
};


void pci_init(void);
void pci_enum(void);
struct PCI_CONF *pci_get_conf(uint16_t vendor_id, uint16_t dev_id);
void pci_write_cmd(struct PCI_CONF *conf);
void pci_read_cmd(struct PCI_CONF *conf);


#endif
