// Generated by mkhdr

#ifndef HEADER_STACKTRACE
#define HEADER_STACKTRACE

#include "file.h"


void init_func_names(void);
void stacktrace(unsigned int max_frames, FILE_T *f);
void stacktrace2(unsigned int max_frames, FILE_T *f, unsigned int *ebp);
char *get_func_name(unsigned int addr);


#endif
