// Generated by mkhdr

#ifndef HEADER_STRING
#define HEADER_STRING

#include <stdarg.h>
#include <stdbool.h>
#include "file.h"

void s_itob(unsigned int n, char *s, bool space);
void s_size(unsigned int size_B, char *s, int n);

int  strlen(const char *s);
char *strcpy(char *s, const char *t);
char *strncpy(char *s, const char *t, int n);
char *strcat(char *s, const char *t);
int  strcmp(const char *s, const char *t);
int  strncmp(const char *s, const char *t, int n);

int  atoi(const char *s);

int  printf(const char *fmt, ...);
int  fprintf(struct FILE_T *f, const char *fmt, ...);
int  snprintf(char *s, unsigned int n, const char *fmt, ...);
int  vfprintf(struct FILE_T *f, const char *fmt, va_list ap);
int  vsnprintf(char *s, unsigned int n, const char *fmt, va_list ap);

int   memcmp(const void *buf1, const void *buf2, unsigned int);
void *memcpy(void *dst, const void *src, unsigned int);
void *memmove(void *dst, const void *src, unsigned int);
void *memset(void *dst, int c, unsigned int count);

// 『エキスパートCプログラミング』p109
#define STRCMP(a, R, b)  (strcmp(a,b) R 0)

#define STRNCMP(a, R, b, n)  (strncmp(a,b,n) R 0)

#endif
