// Generated by mkhdr

#ifndef HEADER_TIME
#define HEADER_TIME

struct DATETIME {
    int year;
    int mon;
    int day;
    int hour;
    int min;
    int sec;
};


void now(struct DATETIME *t);
int dt_str(char *s, int n, struct DATETIME *t);

#endif
