// Generated by mkhdr

#ifndef HEADER_TIME
#define HEADER_TIME

#define MAX_DT_STR 32

struct DATETIME {
    int year;
    int mon;
    int day;
    int hour;
    int min;
    int sec;
    char str[MAX_DT_STR];
};

#endif
