#!/usr/bin/env python
# -*- coding: utf-8 -*-

import sys

HEADS = 16
SECTORS = 63  # sectors per track

def main():
    c = int(input('c: '))
    h = int(input('h: '))
    s = int(input('s: '))

    if s == 0:
        print 'error: s == 0'
        sys.exit(0)

    if s > 63:
        print 'error: s > 63'
        sys.exit(0)

    if h > 15:
        print 'error: h > 15'
        sys.exit(0)

    lba = (h + c*HEADS) * SECTORS + s - 1

    print 'lba = %d' % (lba)


if __name__ == '__main__':
    main()

