#!/usr/bin/env python
# -*- coding: utf-8 -*-

OUT_FILE_NAME = 'funcnames.bin'

import os
import re
import struct
from sys import argv

dot_text_re = re.compile('(.{8}) [tT] (.+)')

def main(symbols_file_name, out_file_name):
    if not os.path.exists(symbols_file_name):
        return

    funcs = []

    for line in open(symbols_file_name, 'r'):
        m = dot_text_re.match(line)

        if m:
            funcs.append([int(m.group(1), 16), m.group(2)])

    funcs.sort(key=lambda x: x[0])

    f = open(out_file_name, 'wb')
    for i in range(len(funcs)):
        f.write(struct.pack('I32s', funcs[i][0], funcs[i][1]))
    f.close()

if __name__ == '__main__':
    main(argv[1], argv[2])

