#!/usr/bin/env python
# -*- coding: utf-8 -*-

'''

機能
----
スタックトレースで呼び出し関数の一覧を出力するときに
アドレスから関数名に変換したいので、そのための対応表をつくる。
入力ファイルはnmから出力されたシンボル一覧で、
出力ファイルはアドレスと関数名の対応が書かれたバイナリ。


使用方法
--------
./mkfuncnames symbols_file output_file


メモ
----
最初はnmの出力でなくmapファイルから対応表をつくっていたが
static宣言されたローカルな関数は表示されなかった。

'''

import os
import struct
from sys import argv


def main(symbols_file_name, out_file_name):
    if not os.path.exists(symbols_file_name):
        return

    funcs = []

    for line in open(symbols_file_name, 'r'):
        addr, typ, name = line.split()

        if typ == 't' or typ == 'T':
            funcs.append([int(addr, 16), name])

    # アドレスでソート
    funcs.sort(key=lambda x: x[0])

    f = open(out_file_name, 'wb')
    for i in range(len(funcs)):
        f.write(struct.pack('I32s', funcs[i][0], funcs[i][1]))
    f.close()

if __name__ == '__main__':
    main(argv[1], argv[2])

