#!/usr/bin/env python
# -*- coding: utf-8 -*-

import os
import re
import struct
import sys
from sys import argv


def main(map_file_name):
    if not os.path.exists(map_file_name):
        return

    f = open(map_file_name, 'rb')
    print struct.unpack('I32s', f.read(36))
    print struct.unpack('I32s', f.read(36))
    print struct.unpack('I32s', f.read(36))
    print struct.unpack('I32s', f.read(36))
    print struct.unpack('I32s', f.read(36))


if __name__ == '__main__':
    if len(argv) != 2:
        print "Usage: readfuncnames funcnames_file"
        sys.exit(0)

    main(argv[1])

